### ISSUE TITLE
Trouble getting Refresh Token

### ISSUE THREAD

**Issue by BoltSwith** [witnessmenow/arduino-spotify-api#73]
I have implemented the "getRefreshToken" example.

I inserted my ClientID and ClientSecret data after creating a developer account on Spotify.
However, when I run the esp32 application and attempt to visit "http://[IP Address]/callback/"   as instructed, I get the following response on my browser

Failed to load token, check serial monitor.

I check the serial monitor and I don't see anything.

What exactly have I got wrong. I feel maybe I missed a step.

In the Setup Instructions provided it's mentioned in the 3rd bullet that:

**You will also need to add a callback URI for authentication process by clicking "Edit Settings", what URI to add will be mentioned in further instructions**

I read the instructions to the end, but couldn't find the "Callback URI for Authentication".
Is the **"Callback URI for Authentication"** same as the **http://[IP Address]/callback/** ??

**Comment by BoltSwith** [comment]
I just tried once again to get the refresh token, but I get the same response:

- Failed to load token, check serial monitor.

And when I checck the serial monitor, I see the message:

```
[385916][E][WebServer.cpp:793] _handleRequest(): request handler not found
File Not Found

URI: /favicon.ico
Method: GET
Arguments: 0
```

What could I be getting wrong?

**Comment by Dijkstra-J** [comment]
I think I figured this one out, I ran into the same problem. 
Instead of going to "http://[IP address]/callback/" go to "http://[IP address]". Then it will load the page with a link (for me at least) which leads to the authentication. After authenticating it will redirect to "http://[IP address]/callback/[refresh token]". 
Hope this helps

**Comment by BoltSwith** [comment]
Thanks very much for the response. I will try this tonight. I hope it works for me too. 

I will provide feedback if successful or not.

Thanks.

**Comment by BoltSwith** [comment]
It worked. I've been able to get the Refresh Token. Thanks.
